import { StyleSheet, Platform } from 'react-native';
import { Colors, FontSize, BorderRadius, Shadows, Spacing } from '../../config/theme';

export const walletStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: Colors.black60,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: BorderRadius.xxl,
    borderTopRightRadius: BorderRadius.xxl,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Platform.OS === 'ios' ? 40 : Spacing.xl,
    ...Shadows.xl,
  },
  handle: {
    width: 44,
    height: 5,
    backgroundColor: Colors.slate300,
    borderRadius: BorderRadius.full,
    alignSelf: 'center',
    marginBottom: Spacing.lg,
  },
  balanceText: {
    fontSize: 42,
    fontWeight: '800',
    textAlign: 'center',
    color: Colors.slate900,
    letterSpacing: -1,
  },
  balanceLabel: {
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.slate500,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: Spacing.lg,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pendingBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    backgroundColor: Colors.warningSoft,
    borderWidth: 1,
    borderColor: Colors.warning + '40',
    borderRadius: BorderRadius.full,
    marginBottom: Spacing.md,
    alignSelf: 'center',
  },
  pendingText: {
    fontSize: FontSize.xs,
    fontWeight: '700',
    color: Colors.warningDark,
  },
  actionRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  actionBtn: {
    flex: 1,
    backgroundColor: Colors.slate50,
    borderWidth: 1,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIcon: {
    marginBottom: 4,
  },
  actionLabel: {
    fontSize: FontSize.xs,
    fontWeight: '700',
    color: Colors.slate800,
  },
  sectionTitle: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.slate900,
    marginBottom: Spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  balanceInfo: {
    fontSize: FontSize.xs,
    color: Colors.slate500,
    marginTop: 4,
    marginBottom: Spacing.sm,
    fontWeight: '600',
  },
  errorText: {
    fontSize: FontSize.xs,
    color: Colors.error,
    marginTop: 4,
    fontWeight: '600',
  },
  verifyingText: {
    fontSize: FontSize.xs,
    color: Colors.slate500,
    marginTop: 4,
    fontWeight: '600',
  },
  verifiedText: {
    fontSize: FontSize.xs,
    color: Colors.successDark,
    marginTop: 4,
    fontWeight: '600',
  },
  txRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.sm,
  },
  txIcon: {
    width: 40,
    height: 40,
    backgroundColor: Colors.slate100,
    borderRadius: BorderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txIconText: {
    fontSize: 18,
  },
  txInfo: {
    flex: 1,
    marginLeft: Spacing.md,
  },
  txType: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.slate900,
  },
  txStatus: {
    fontSize: FontSize.xs,
    color: Colors.slate500,
    marginTop: 2,
  },
  txReference: {
    fontSize: 10,
    color: Colors.slate400,
    marginTop: 1,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  txAmount: {
    fontSize: FontSize.md,
    fontWeight: '700',
  },
  closeBtn: {
    marginTop: Spacing.md,
    alignItems: 'center',
    paddingVertical: Spacing.sm,
  },
  closeBtnText: {
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.slate500,
  },
  sheetTitle: {
    fontSize: FontSize.xxl,
    fontWeight: '800',
    color: Colors.slate900,
    letterSpacing: -0.5,
  },
  sheetSubtitle: {
    fontSize: FontSize.sm,
    color: Colors.slate500,
    marginTop: 2,
    marginBottom: Spacing.lg,
  },
  quickRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.xs,
    marginBottom: Spacing.md,
  },
  quickChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: Colors.slate50,
    borderWidth: 1,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.full,
  },
  quickChipActive: {
    backgroundColor: Colors.slate900,
    borderColor: Colors.slate900,
  },
  quickChipText: {
    fontWeight: '700',
    fontSize: FontSize.sm,
    color: Colors.slate700,
  },
  quickChipTextActive: {
    color: Colors.white,
  },
  input: {
    backgroundColor: Colors.slate50,
    borderWidth: 1.5,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
    fontSize: FontSize.md,
    marginBottom: Spacing.sm,
    color: Colors.slate900,
  },
  feeBox: {
    padding: Spacing.md,
    backgroundColor: Colors.slate50,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.slate200,
    marginVertical: Spacing.md,
  },
  feeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 4,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.slate200,
    marginVertical: Spacing.sm,
  },
  primaryBtn: {
    backgroundColor: Colors.slate900,
    paddingVertical: 16,
    borderRadius: BorderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.xs,
    ...Shadows.md,
  },
  disabledBtn: {
    opacity: 0.5,
  },
  primaryBtnText: {
    color: Colors.white,
    fontWeight: '800',
    fontSize: FontSize.md,
    letterSpacing: 0.3,
  },
  cancelBtn: {
    marginTop: Spacing.md,
    alignItems: 'center',
    paddingVertical: Spacing.xs,
  },
  cancelBtnText: {
    color: Colors.slate500,
    fontSize: FontSize.sm,
    fontWeight: '600',
  },
  bankSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.slate50,
    borderWidth: 1.5,
    borderColor: Colors.slate200,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
    marginBottom: Spacing.sm,
  },
  bankSelectorText: {
    fontWeight: '700',
    fontSize: FontSize.md,
    color: Colors.slate900,
  },
  bankSelectorArrow: {
    color: Colors.slate500,
    fontSize: FontSize.sm,
  },
  bankItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.slate100,
  },
  bankItemText: {
    fontSize: FontSize.md,
    fontWeight: '600',
    color: Colors.slate800,
  },
  checkmark: {
    fontWeight: '800',
    color: Colors.primaryAccent,
  },
});
