import { StyleSheet } from 'react-native';
import { Colors, FontSize, BorderRadius, Shadows } from '../../config/theme';

export const walletStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 20,
    paddingBottom: 32,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.grey,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  balanceText: {
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    color: Colors.black,
  },
  balanceLabel: {
    fontSize: 14,
    color: Colors.grey,
    textAlign: 'center',
    marginBottom: 16,
  },
  pendingBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,160,0,0.1)',
    borderWidth: 1,
    borderColor: Colors.warning,
    borderRadius: BorderRadius.sm,
    marginBottom: 16,
    alignSelf: 'center',
  },
  pendingText: { fontSize: 12, color: Colors.warning },
  actionRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  actionBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: Colors.black,
    borderRadius: BorderRadius.sm,
    paddingVertical: 14,
    alignItems: 'center',
  },
  actionIcon: { fontSize: 24 },
  actionLabel: { fontSize: 12, fontWeight: 'bold', marginTop: 4 },
  sectionTitle: { fontWeight: 'bold', fontSize: 14, marginBottom: 8 },
  txRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  txIcon: {
    width: 36,
    height: 36,
    borderWidth: 1.5,
    borderColor: Colors.black,
    borderRadius: BorderRadius.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txIconText: { fontSize: 16 },
  txInfo: { flex: 1, marginLeft: 12 },
  txType: { fontWeight: 'bold', fontSize: 13 },
  txStatus: { fontSize: 11, color: Colors.grey },
  txAmount: { fontWeight: 'bold', fontSize: 14 },
  closeBtn: { marginTop: 12, alignItems: 'center' },
  closeBtnText: { fontSize: FontSize.md, color: Colors.grey },
  sheetTitle: { fontSize: 22, fontWeight: 'bold' },
  sheetSubtitle: { fontSize: 14, color: Colors.grey, marginBottom: 20 },
  quickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  quickChip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: Colors.black,
    borderRadius: BorderRadius.sm,
  },
  quickChipActive: { backgroundColor: Colors.black },
  quickChipText: { fontWeight: 'bold', color: Colors.black },
  quickChipTextActive: { color: Colors.white },
  input: {
    borderWidth: 2,
    borderColor: Colors.black,
    borderRadius: BorderRadius.sm,
    padding: 14,
    fontSize: FontSize.md,
    marginBottom: 12,
    color: Colors.black,
  },
  feeBox: {
    padding: 12,
    backgroundColor: 'rgba(245,245,245,0.5)',
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
    marginBottom: 16,
  },
  feeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 2,
  },
  divider: { height: 1, backgroundColor: Colors.lightGrey, marginVertical: 6 },
  primaryBtn: {
    backgroundColor: Colors.black,
    paddingVertical: 16,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
  },
  disabledBtn: { opacity: 0.6 },
  primaryBtnText: { color: Colors.white, fontWeight: 'bold', fontSize: 16 },
  cancelBtn: { marginTop: 12, alignItems: 'center' },
  cancelBtnText: { color: Colors.grey, fontSize: FontSize.md },
  bankSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.black,
    borderRadius: BorderRadius.sm,
    padding: 14,
    marginBottom: 12,
  },
  bankSelectorText: { fontWeight: 'bold', color: Colors.black },
  bankSelectorArrow: { color: Colors.black },
  bankItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.lightGrey,
  },
  bankItemText: { fontSize: FontSize.md, color: Colors.black },
  checkmark: { fontWeight: 'bold', color: Colors.black },
});
